### ISSUE TITLE
Neither the export json or export dat works

### ISSUE THREAD

**Issue by MrLinio** [NetroScript/Graveyard-Keeper-Savefile-Editor#5] opened 2018-08-28 16:24 UTC
On the current zip application, neither the export to json or export to dat works.

**Comment by MrLinio** [comment] 2018-08-28 16:28
Actually it's working on and off...
Strange...
I'll continue investigating.

**Comment by NetroScript** [comment] 2018-08-28 16:37
Do you have any errors in the console window?

**Comment by MrLinio** [comment] 2018-08-28 16:48
None whatsoever sorry.
I don't really understand the behaviour. I'm wondering if it's just an issue of "performance", there's no visual return that the system is processing anything, so when I click I don't know whether it's doing anything or not.
It did work that one time, but after that nothing.

On another note, I don't know if you take request, but I was wondering if there could be a way to "reset" the NPC, specially the donkey, a lot of people are experiencing issues where the donkey is "stuck", and saved as is, and no way to play anymore... :/

**Comment by NetroScript** [comment] 2018-08-28 17:37
I would have no problem implementing request in the current application, but the problem is knowing where in the save file is stored everything. And I don't really have the time to test all of that - if people take the time and test which values influence the behavior, I would take the time and implement an automated way in the application.
Considering your problem it seems difficult for me to help you because I can't recreate the problem. Are the files not created at all? And does your console not have a message like "Dumping JSON to: <path>" when clicking export JSON? I can't imagine it not working without showing any error at all. If that is the case I would assume the GUI has a mistake, meaning you get a JavaScript error instead of a Python error - to check that press F12 in the application and go to the tab "Console" and check if there are any red errors. (Ignore errors about /rsc/<img>.png, they are intended)

**Comment by NetroScript** [comment] 2018-08-30 19:29
So you still have a problem? If not I will close this at some point, considering no updates on your side. If the issue still persists, feel free to bring it up again.

**Comment by MrLinio** [comment] 2018-08-31 07:29
Yes, I think the problem is still there, but I won't be able to use the software anyway so you can close it if you don't feel like wasting time on this.

**Comment by NetroScript** [comment] 2018-08-31 10:00
It's not that I feel like it would be wasting time, it is important for me that the base functionality works for everyone, but with the given information I can't really help.

**Comment by OnyxSpartanII** [comment] 2018-09-01 03:08
I'm experiencing the same issue, but I do have error messages in my console. This is with the Windows executable.

What is interesting is that the args section has been different nearly every time I've loaded up the program. Once it's said something about additional storage, sometimes it's saveslot or something similar when I try to save to slot, and then when I try to save as a custom .dat file, the error arg is savecustomslot (or something similar).

Traceback (most recent call last):
  File "J:\Programme\Python64\lib\site-packages\gevent\greenlet.py", line 536, in run
  File "J:\Programme\Python64\lib\site-packages\eel\__init__.py", line 191, in _process_message
  File "J:\Projekte\GitHub\Graveyard Keeper Savefile Editor\main.py", line 116, in saveslot
  File "J:\Projekte\GitHub\Graveyard Keeper Savefile Editor\main.py", line 219, in modifysave
IndexError: list index out of range
Fri Aug 31 22:06:19 2018 <Greenlet at 0x1d83a8eb340: _process_message({'call': 2.328665083779632, 'args': [{'technologie, <geventwebsocket.websocket.WebSocket object at 0x0)> failed with IndexError

Traceback (most recent call last):
  File "J:\Programme\Python64\lib\site-packages\gevent\greenlet.py", line 536, in run
  File "J:\Programme\Python64\lib\site-packages\eel\__init__.py", line 191, in _process_message
  File "J:\Projekte\GitHub\Graveyard Keeper Savefile Editor\main.py", line 140, in savecustomsavefile
  File "J:\Projekte\GitHub\Graveyard Keeper Savefile Editor\main.py", line 219, in modifysave
IndexError: list index out of range
Fri Aug 31 22:06:31 2018 <Greenlet at 0x1d82e905d58: _process_message({'call': 3.087723769068756, 'args': [{'technologie, <geventwebsocket.websocket.WebSocket object at 0x0)> failed with IndexError

**Comment by NetroScript** [comment] 2018-09-01 14:47
This most likely happens because you close the window of a save file too fast again. If you open a save slot it gets loaded into memory, if you close it, it gets unloaded. If you have the same save open in another window and close the first, the second window won't be able to access the save file anymore. Can this be the case?

**Comment by OnyxSpartanII** [comment] 2018-09-01 15:27
No, I have the save open in only one window. The only windows relating to the program are the console window, the save load menu, and then the actual save editor menu. One instance of each, no other copies of the executable are running.

**Comment by NetroScript** [comment] 2018-09-01 18:13
If you have an editor window open of a save file, before clicking save, if you type `window.location.hash` in the console (press F12, go to tab Console and enter it there) - what does it say and what is the memory usage of the application?

**Comment by OnyxSpartanII** [comment] 2018-09-01 19:11
Memory usage is 0.5 MB in Task Manager. Total system usage is presently at 67%.

window.location.hash
"#slot|1792217613|1"

**Comment by NetroScript** [comment] 2018-09-01 19:29
How much memory do you have? Does it say something about unloading the save file? Like it is written somewhere, a single save file takes more than 100 MB RAM meaning if you only have a usage of .5 MB it unloaded the save for some reason. (This normally should only happen because you close the window of the loaded save)

**Comment by OnyxSpartanII** [comment] 2018-09-01 20:01
Edited above to say I have 16GB of RAM. There's nothing extra in the devtools menu when I do anything.

Fascinating, it's now working. The only change I made was previously I was attempting to edit my inventory when I had nothing in it. I then played a bit more, and saved and quit with some items in my inventory. This time adding items succeeded.

**Comment by NetroScript** [comment] 2018-09-01 20:07
Ah, now I know what the problem was - If you add an item to your inventory it duplicates the last item you have and modifies it's attributes, but you had no "fallback" item meaning it tried duplicating non existent objects, causing an error.

**Comment by NetroScript** [comment] 2018-09-01 22:05
Should be fixed with 0.1.6

**Closed by NetroScript** 2018-09-01 22:05 UTC
