### ISSUE TITLE
Too small [BUG]

### ISSUE THREAD

**Issue by klown-code** [NetroScript/Graveyard-Keeper-Savefile-Editor#56] opened 2019-11-02 12:14 UTC
**Describe the bug**
Could you make your interface even bigger?
Because 3 lines only make 95% of my screen at 3440x1440...

**To Reproduce**
Launch the application

**Screenshots**
![image](https://user-images.githubusercontent.com/55700834/68070738-7efb2c80-fd72-11e9-8784-e163f52e5717.png)

**Comment by NetroScript** [comment] 2019-11-02 16:02
Because the application uses a browser as a GUI you should be able to use `CTRL + Mouse Wheel` to zoom in and out. The default behavior of the browser should be that it stays zoomed in. It only maybe won't stay zoomed in if it uses a different random port each time. Then you could set a port in the settings which it should use. (Although on chrome it only depends on domain and not on the port).
I could also manually set a specific zoom level in chrome (which is currently 1.5), but Firefox doesn't support it. If the zooming in on the browser level doesn't work write me again and I might try to make some changes to the CSS (media queries) to make the higher resolution better.

**Comment by c1ph3rl1nux** [comment] 2020-12-02 07:41
@klown-code 
I can confirm that zooming into the GKSE browser gui works perfectly fine. I have multiple monitors with different resolutions, tested it in Chrome, Firefox, Opera, Vivaldi & Brave and had no issues. Unless you are using an outdated browser. Bug report can be closed for now.

**Comment by NetroScript** [comment] 2020-12-03 07:12
Closing considering the statement of @c1ph3rl1nux - Should there be new problems at some point, feel free to reopen.

**Closed by NetroScript** 2020-12-03 07:12 UTC
Labels: enhancement

**Comment by klownk** [comment] 2020-12-03 11:33
lol
